{{if eq .Values.psp.enabled "on" }}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "eric-ccsm.sa-psp.service-account.name" . }}
{{- include "eric-ccsm.helm-labels" . | indent 2 }}
{{- include "eric-ccsm.helm-annotations" . | indent 2 }}

{{ end }}
