{{- if .Values.global.vtapagent.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "eric-ccsm.tap-agent.name" . }}
{{- include "eric-ccsm.helm-labels" . | indent 2 }}
{{- include "eric-ccsm.helm-annotations" . | indent 2 }}
data:
{{- if .Release.IsInstall }}
  sftpConfig.json: |-
    W10K
{{- else }}
{{- $dict := (lookup "v1" "Secret" .Release.Namespace  (include "eric-ccsm.tap-agent.name" .)  ).data }}
  sftpConfig.json: |-
{{ tpl (get $dict "sftp_config.json") . | indent 4 }}
{{- end }}
{{- end }}
