{{ if eq .Values.psp.enabled "on" }}

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "eric-ccsm.sa-psp.role.name" . }}
  namespace: {{ .Release.Namespace }}
{{- include "eric-ccsm.helm-labels" . | indent 2 }}
{{- include "eric-ccsm.helm-annotations" . | indent 2 }}
rules:
  - apiGroups:
      - policy
    resources:
      - podsecuritypolicies
    resourceNames:
      - {{ .Values.ccsm.psp.policy }}
    verbs:
      - use

{{end}}
